///////////////////////////////////////////////////////////
//  Groupe.cs
//  Implementation of the Class Groupe
//  Generated by Enterprise Architect
//  Created on:      11-juin-2015 10:49:21
//  Original author: Quentin
///////////////////////////////////////////////////////////




namespace System {
	public class Groupe {

		private string Nom;

		public Groupe(){

		}

		~Groupe(){

		}

		public virtual void Dispose(){

		}

	}//end Groupe

}//end namespace System