///////////////////////////////////////////////////////////
//  Historique.cs
//  Implementation of the Class Historique
//  Generated by Enterprise Architect
//  Created on:      17-juin-2015 09:38:57
//  Original author: Omar
///////////////////////////////////////////////////////////
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Modelisator.Model;


namespace Modelisator.Model {
	public class Historique {

        public List<Contexte> Contextes;

		public Historique(){		}


	}//end Historique

}//end namespace Modelisator.Model