///////////////////////////////////////////////////////////
//  Sauvegarde.cs
//  Implementation of the Class Sauvegarde
//  Generated by Enterprise Architect
//  Created on:      11-juin-2015 10:49:21
//  Original author: Quentin
///////////////////////////////////////////////////////////




using Modelisator.Model;
namespace Modelisator.Model
{
	public class Sauvegarde {

		private string Nom;
		//private date Date;
		private string Chemin;
		public Produit m_Produit;

		public Sauvegarde(){

		}

		~Sauvegarde(){

		}

		public virtual void Dispose(){

		}

		public void import(){

		}

		public void export(){

		}

	}//end Sauvegarde

}//end namespace System