///////////////////////////////////////////////////////////
//  Contexte.cs
//  Implementation of the Class Contexte
//  Generated by Enterprise Architect
//  Created on:      17-juin-2015 09:38:57
//  Original author: Quentin
///////////////////////////////////////////////////////////




using Modelisator.Model;
namespace Modelisator.Model {
	public class Contexte {

		private Produit ListeProduit{
			//read property
			get{;}
			//write property
			set{;}
		}
		public Produit m_Produit;

		public Contexte(){

		}

		~Contexte(){

		}

		public virtual void Dispose(){

		}

		public Produit ListeProduit{
			get{
				return ListeProduit;
			}
			set{
				ListeProduit = value;
			}
		}

	}//end Contexte

}//end namespace Modelisator.Model