///////////////////////////////////////////////////////////
//  GrandeurPhysique.cs
//  Implementation of the Class GrandeurPhysique
//  Generated by Enterprise Architect
//  Created on:      17-juin-2015 09:38:57
///////////////////////////////////////////////////////////




using Modelisator.Model;
namespace Modelisator.Model {
	public class GrandeurPhysique {

		private bool Calcule{
			//read property
			get{;}
			//write property
			set{;}
		}
		private string Description{
			//read property
			get{;}
			//write property
			set{;}
		}
		private bool EstPremier{
			//read property
			get{;}
			//write property
			set{;}
		}
		private string Nom{
			//read property
			get{;}
			//write property
			set{;}
		}
		private bool Selectionne{
			//read property
			get{;}
			//write property
			set{;}
		}
		private string Unite{
			//read property
			get{;}
			//write property
			set{;}
		}
		private double Valeur{
			//read property
			get{;}
			//write property
			set{;}
		}
		public List<> m_Produit;
		public List<> m_Equation;

		public GrandeurPhysique(){

		}

		~GrandeurPhysique(){

		}

		public virtual void Dispose(){

		}

		public bool Calcule{
			get{
				return Calcule;
			}
			set{
				Calcule = value;
			}
		}

		public string Description{
			get{
				return Description;
			}
			set{
				Description = value;
			}
		}

		public bool EstPremier{
			get{
				return EstPremier;
			}
			set{
				EstPremier = value;
			}
		}

		public string Nom{
			get{
				return Nom;
			}
			set{
				Nom = value;
			}
		}

		public bool Selectionne{
			get{
				return Selectionne;
			}
			set{
				Selectionne = value;
			}
		}

		public string Unite{
			get{
				return Unite;
			}
			set{
				Unite = value;
			}
		}

		public double Valeur{
			get{
				return Valeur;
			}
			set{
				Valeur = value;
			}
		}

	}//end GrandeurPhysique

}//end namespace Modelisator.Model