///////////////////////////////////////////////////////////
//  Historique.cs
//  Implementation of the Class Historique
//  Generated by Enterprise Architect
//  Created on:      17-juin-2015 09:38:57
//  Original author: Omar
///////////////////////////////////////////////////////////




using Modelisator.Model;
namespace Modelisator.Model {
	public class Historique {

		private Contexte ListeContext{
			//read property
			get{;}
			//write property
			set{;}
		}
		public Contexte m_Contexte;

		public Historique(){

		}

		~Historique(){

		}

		public virtual void Dispose(){

		}

	}//end Historique

}//end namespace Modelisator.Model