///////////////////////////////////////////////////////////
//  Produit.cs
//  Implementation of the Class Produit
//  Generated by Enterprise Architect
//  Created on:      17-juin-2015 09:38:57
///////////////////////////////////////////////////////////




namespace Modelisator.Model {
	public class Produit {

		private string Description{
			//read property
			get{;}
			//write property
			set{;}
		}
		private string Nom{
			//read property
			get{;}
			//write property
			set{;}
		}
		private bool Selectionne{
			//read property
			get{;}
			//write property
			set{;}
		}

		public Produit(){

		}

		~Produit(){

		}

		public virtual void Dispose(){

		}

		public string Description{
			get{
				return Description;
			}
			set{
				Description = value;
			}
		}

		public string Nom{
			get{
				return Nom;
			}
			set{
				Nom = value;
			}
		}

		public bool Selectionne{
			get{
				return Selectionne;
			}
			set{
				Selectionne = value;
			}
		}

	}//end Produit

}//end namespace Modelisator.Model