///////////////////////////////////////////////////////////
//  Contexte.cs
//  Implementation of the Class Contexte
//  Generated by Enterprise Architect
//  Created on:      11-juin-2015 10:49:20
//  Original author: Quentin
///////////////////////////////////////////////////////////




using Modelisator.Model;
namespace Modelisator.Model
{
	public class Contexte {

		private Produit ListeProduit;
		private Produit Historique;
		public Produit m_Produit;

		public Contexte(){

		}

		~Contexte(){

		}

		public virtual void Dispose(){

		}

	}//end Contexte

}//end namespace System