///////////////////////////////////////////////////////////
//  Equation.cs
//  Implementation of the Class Equation
//  Generated by Enterprise Architect
//  Created on:      17-juin-2015 09:38:57
//  Original author: Omar and Taha
///////////////////////////////////////////////////////////
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;



namespace Modelisator.Model {
	public class Equation {

		public Equation()
        {
        }

        private int m_NbrGP;

        private int m_NbrGPConnus;
        
		public double Calculer(){

			return 0;
		}

		public int NbrGP{
			get{
                return m_NbrGP;
			}
			set{
                m_NbrGP = value;
			}
		}

		public int NbrGPConnus{
			get{
                return m_NbrGPConnus;
			}
			set{
                m_NbrGPConnus = value;
			}
		}

        /// <summary>
        /// calcul of Pressure of gas : p(MPa)
        /// </summary>
        /// <param name="X1">X1 : Coefficient of variation of the pressure (dimensionless)</param>
        /// <param name="Tmax">Tmax : Maximum temperature (°C)</param>
        /// <param name="p0">p0 : Pressure of a liquid gas at 15°C (MPa)</param>
        /// <returns></returns>
 
        static double equation1(double X1, double Tmax, double p0)
        {
            double p;
            p = X1 * (Math.Pow(Tmax - 15, 2)) + p0;
            return p;
        }

        /// <summary>
        /// calcul ofPressure of a liquid gas at 15°C (MPa)
        /// </summary>
        /// <param name="X1">X1 : Coefficient of variation of the pressure (dimensionless)</param>
        /// <param name="Tmax">Tmax : Maximum temperature (°C)</param>
        /// <param name="p">p :  Pressure of gas (MPa)</param>
        /// <returns></returns>
        static double equation23(double X1, double Tmax, double p)
        {
            double p0;
            p0 = p - (X1 * (Math.Pow(Tmax - 15, 2))) ;
            return p0;
        }

        /// <summary>
        /// calcul of (MPa)Coefficient of variation of the pressure (dimensionless)
        /// </summary>
        /// <param name="p">p : Pressure of gas (Mpa)</param>
        /// <param name="Tmax">Tmax : Maximum temperature (°C)</param>
        /// <param name="p0">p0 : Pressure of a liquid gas at 15°C (MPa)</param>
        /// <returns></returns>
 
        static double equation24(double p, double Tmax, double p0)
        {
            double X1;
            if (Tmax != 15)
                X1 = (p - p0) / (Math.Pow(Tmax - 15, 2));
            else
                X1 = -1;
            return X1;
        }

        /// <summary>
        /// calcul of Maximum temperature (°C)
        /// </summary>
        /// <param name="X1">X1 : Coefficient of variation of the pressure (dimensionless)</param>
        /// <param name="p">p : Pressure of gas (MPa)</param>
        /// <param name="p0">p0 : Pressure of a liquid gas at 15°C (MPa)</param>
        /// <returns></returns>
 
        static double equation25(double X1, double p, double p0)
        {
            double Tmax;
            if (X1 != 0)
                Tmax = Math.Sqrt((p - p0) / X1) + 15;
            else 
                Tmax = -1;
            return Tmax;
        }


        /// <summary>
        ///  calcul of Expansion of gas 
        /// </summary>
        /// <param name="alpha_gas">alpha_gas : Volumetric gaz expansion coefficient (% / °C)</param>
        /// <param name="Tmax">Tmax : Maximum temperature (°C)</param>
        /// <returns></returns>

        static double equation2(double alpha_gas, double Tmax)
        {
            double dV;
            dV = alpha_gas * (Tmax - 15);
            return dV;
        }


        /// <summary>
        /// calcul of Maximum temperature (°C)
        /// </summary>
        /// <param name="alpha_gas">alpha_gas : Volumetric gaz expansion coefficient (% / °C)</param>
        /// <param name="dV">dV : Expansion of gas</param>
        /// <returns></returns>
  
        static double equation26(double alpha_gas, double dV)
        {
            double Tmax;
            if (alpha_gas != 0)
                Tmax = (dV / alpha_gas) + 15;
            else
                Tmax = -1;
            return Tmax;
        }

        /// <summary>
        ///  calcul of  Volumetric gaz expansion coefficient (% / °C)
        /// </summary>
        /// <param name="Tmax">Tmax : Maximum temperature (°C)</param>
        /// <param name="dV">dV : Expansion of gas</param>
        /// <returns></returns>

        static double equation26bis(double Tmax, double dV)
        {
            double alpha_gas;
            if (Tmax != 15)
                alpha_gas = (dV / (Tmax-15));
            else
                alpha_gas = -1;
            return alpha_gas;
        }


        /// <summary>
        /// calcul of Applied strass (Mpa)
        /// </summary>
        /// <param name="p">p : Pressure of gas (Mpa)</param>
        /// <param name="R">R : Radius (mm)</param>
        /// <param name="t">t : Thickness (mm)</param>
        /// <returns></returns>
 
        static double equation3(double p, double R, double t)
        {
            double sigma;
            if (t != 0)
                sigma = (p * R) / t;
            else
                sigma = -1;
            return sigma;

        }

        /// <summary>
        /// calcul of Pressure of gas (Mpa)
        /// </summary>
        /// <param name="sigma">sigma : Applied strass (Mpa)</param>
        /// <param name="R">R : Radius (mm)</param>
        /// <param name="t">t : Thickness (mm)</param>
        /// <returns></returns>
 
        static double equation27(double sigma, double R, double t)
        {
            double p;
            if (R != 0)
                p = (sigma * t) / R;
            else
                p = -1;
            return p;

        }

        /// <summary>
        /// calcul of Radius (mm)
        /// </summary>
        /// <param name="sigma">sigma : Applied strass (Mpa)</param>
        /// <param name="p">p : Pressure of gas (Mpa)</param>
        /// <param name="t">t : Thickness (mm)</param>
        /// <returns></returns>
 
        static double equation28(double sigma, double p, double t)
        {
            double R;
            if (p != 0)
                R = (sigma * t) / p;
            else
                R = -1;
            return R;
        }


        /// <summary>
        /// calcul of Thickness (mm)
        /// </summary>
        /// <param name="sigma">sigma : Applied strass (Mpa)</param>
        /// <param name="p">p : Pressure of gas (Mpa)</param>
        /// <param name="R">R : Radius (mm)</param>
        /// <returns></returns>
 
        static double equation29(double sigma, double p, double R)
        {
            double t;
            if (sigma != 0)
                t = (p * R) / sigma;
            else
                t = -1;
            return t;
        }

        /// <summary>
        /// calcul of Useful thichness (mm)
        /// </summary>
        /// <param name="p">p : Pressure of gas (Mpa)</param>
        /// <param name="R">R : Radius (mm)</param>
        /// <param name="sigma_y">sigma_y : Yield strenght (Mpa)</param>
        /// <returns></returns>
 
        static double equation4(double p, double R, double sigma_y)
        {
            double tu;
            if (sigma_y != 0)
                tu = (p * R) / sigma_y;
            else
                tu = -1;
            return tu;
        }



        /// <summary>
        /// calcul of Pressure of gas (Mpa)
        /// </summary>
        /// <param name="tu">tu : Useful thichness (mm)</param>
        /// <param name="R">R : Radius (mm)</param>
        /// <param name="sigma_y">sigma_y : Yield strenght (Mpa)</param>
        /// <returns></returns>
 
        static double equation30(double tu, double R, double sigma_y)
        {
            double p;
            if (R != 0)
                p = (tu * sigma_y) / R;
            else
                p = -1;
            return p;
        }

        /// <summary>
        /// calcul of Radius (mm)
        /// </summary>
        /// <param name="tu">tu : Useful thichness (mm)</param>
        /// <param name="p">p : Pressure of gas (Mpa)</param>
        /// <param name="sigma_y">sigma_y : Yield strenght (Mpa)</param>
        /// <returns></returns>
        static double equation31(double tu, double p, double sigma_y)
        {
            double R;
            if (p != 0)
                R = (tu * sigma_y) / p;
            else
                R
                    = -1;
            return R;
        }

        /// <summary>
        /// calcul of Yield strenght (Mpa)
        /// </summary>
        /// <param name="tu">tu : Useful thichness (mm)</param>
        /// <param name="p">p : Pressure of gas (Mpa)</param>
        /// <param name="R">R : Radius (mm)</param>
        /// <returns></returns>
 
        static double equation32(double tu, double p, double R)
        {
            double sigma_y;
            if (tu != 0)
                sigma_y = (p * R) / tu;
            else
                sigma_y
                    = -1;
            return sigma_y;
        }

        /// <summary>
        /// calcul of Excess thickness
        /// </summary>
        /// <param name="t">t : Thickness (mm)</param>
        /// <param name="tu">tu : Useful thichness (mm)</param>
        /// <returns></returns>
 
        static double equation5(double t, double tu)
        {
            double delta_t = t - tu;
            return delta_t;
        }

        /// <summary>
        /// calcul of Lifespan (year)
        /// </summary>
        /// <param name="t">t : Thickness (mm)</param>
        /// <param name="tu">tu : Useful thichness (mm)</param>
        /// <param name="C">C : Thickness loss (mm/year)</param>
        /// <returns></returns>
 
        static double equation6(double t, double tu, double C)
        {
            double lifespan;
            if (C != 0)
                lifespan = (t - tu) / C;
            else
                lifespan = -1;
            return lifespan;
        }

        /// <summary>
        /// calcul of Stress intensity factor for flaw size to useful thickness (Mpa racine(m))
        /// </summary>
        /// <param name="alpha">alpha : Correction factor (dimensionless)</param>
        /// <param name="sigma_y">sigma_y : Yield strenght (Mpa)</param>
        /// <param name="tu">tu : Useful thichness (mm)</param>
        /// <returns></returns>
 
        static double equation7(double alpha, double sigma_y, double tu)
        {
            double KI = alpha * sigma_y * Math.Sqrt(tu);
            return KI;
        }

        /// <summary>
        /// calcul of Force of punching (N)
        /// </summary>
        /// <param name="nu">nu : Radius of punching hole (m)</param>
        /// <param name="t">t : Thickness (mm)</param>
        /// <param name="sigma_y">sigma_y : Yield strenght (Mpa)</param>
        /// <returns></returns>
 
        static double equation8(double nu, double t, double sigma_y)
        {
            double Fp = 2 * Math.PI * t * sigma_y;
            return Fp;
        }

        /// <summary>
        /// calcul of Volume (mm3)
        /// </summary>
        /// <param name="R">R : Radius (mm)</param>
        /// <param name="h">h : Height (mm)</param>
        /// <returns></returns>
 
        static double equation9(double R, double h)
        {
            double V = (Math.PI * Math.Pow(R, 2) * h);
            return V;
        }

        /// <summary>
        /// calcul of Usuful mass (Kg)
        /// </summary>
        /// <param name="V">V : Volume (mm3)</param>
        /// <param name="dV">dV : Expansion of gas </param>
        /// <param name="pg">pg : density of gaz (kg/m3)</param>
        /// <returns></returns>
 
        static double equation10(double V, double dV, double pg)
        {
            double Mu = V * (1 - dV) * pg;
            return Mu;
        }

        /// <summary>
        /// calcul of Surface (mm2)
        /// </summary>
        /// <param name="R">R : Radius (mm)</param>
        /// <param name="h">h : Height (mm)</param>
        /// <returns></returns>
 
        static double equation11(double R, double h)
        {
            double S = (Math.PI * R * h) + (2 * Math.PI * Math.Pow(R, 2));
            return S;
        }

        /// <summary>
        /// calcul of Empty mass (Kg)
        /// </summary>
        /// <param name="S">S : Surface (mm2)</param>
        /// <param name="t">t : Thickness (mm)</param>
        /// <param name="ro">ro : Density of material (kg/m3)</param>
        /// <returns></returns>
 
        static double equation12(double S, double t, double ro)
        {
            double Mv = S * t * ro;
            return Mv;
        }

        /// <summary>
        /// calcul of Total mass (Kg)
        /// </summary>
        /// <param name="Mv">Mv : Empty mass (Kg)</param>
        /// <param name="Mg">Mg : ...</param>
        /// <returns></returns>
 
        static double equation13(double Mv, double Mg)
        {
            double Mt = Mv + Mg;
            return Mt;
        }

        /// <summary>
        /// calcul of Perimeter (mm)
        /// </summary>
        /// <param name="R">// R : Radius (mm)</param>
        /// <returns></returns>
 
        static double equation14(double R)
        {
            double P = 2 * Math.PI * R;
            return P;
        }

        /// <summary>
        /// calcul of cost crimping (€)
        /// </summary>
        /// <param name="P">P : Perimeter (mm)</param>
        /// <param name="cs">cs : cost/m (€/m)</param>
        /// <returns></returns>
 
        static double esuation15(double P, double cs)
        {
            double Cs = P * cs;
            return Cs;
        }

        /// <summary>
        /// calcul of cost of material (€)
        /// </summary>
        /// <param name="Mv">Mv : Empty mass (Kg)</param>
        /// <param name="cm">cm : cost/m (€/kg)</param>
        /// <returns></returns>
 
        static double equation16(double Mv, double cm)
        {
            double Cm = Mv * cm;
            return Cm;
        }

        /// <summary>
        /// calcul of Coast of coating (€)
        /// </summary>
        /// <param name="S">S : Surface (mm2)</param>
        /// <param name="cr">cr : cost/m2 (€/m2)</param>
        /// <returns></returns>
 
        static double equation17(double S, double cr)
        {
            double Cr = S * cr;
            return Cr;
        }

        /// <summary>
        /// calcul of Cost of deep drawing
        /// </summary>
        /// <returns></returns>
 
        static double equation18()
        {
            return 0;
        }

        /// <summary>
        /// calcul of total coast (€)
        /// </summary>
        /// <param name="Cm">Cm : cost of material (€)</param>
        /// <param name="Cs">Cs : cost crimping (€)</param>
        /// <param name="Cr">Cr : Coast of coating (€)</param>
        /// <param name="Ce">Ce : Cost of deep drawing</param>
        /// <returns></returns>
 
        static double equation19(double Cm, double Cs, double Cr, double Ce)
        {
            Ce = 0;
            double Ct = Cm + Cs + Cr + Ce;
            return Ct;
        }

        /// <summary>
        /// calcul of Rate of heat flow (W)
        /// </summary>
        /// <param name="Tmin">Tmin : Minimum temperature (°C)</param>
        /// <param name="T0">T0 : Boiling point : (°C)</param>
        /// <param name="lambda">Lambda : Coefficient of thermal conductivity ( W.m-1.K-1)</param>
        /// <param name="t">t : Thickness (mm)</param>
        /// <param name="S">S : Surface (mm2)</param>
        /// <returns></returns>
 
        static double equation20(double Tmin, double T0, double lambda, double t, double S)
        {
            double Q = lambda * ((Tmin - T0) / t) * S;
            return Q;
        }

        /// <summary>
        /// calcul of Volumetric flow rate of gaz (Kg/s)
        /// </summary>
        /// <param name="Q">Q : Rate of heat flow (W)</param>
        /// <param name="Cl">Cl : Latent heat of vaporization of gaz (J/Kg)</param>
        /// <returns></returns>
 
        static double equation21(double Q, double Cl)
        {
            double D;
            if (Cl != 0)
                D = Q / Cl;
            else
                D = -1;
            return D;
        }

        /// <summary>
        /// calcul of Power (W)
        /// </summary>
        /// <param name="D">D : Volumetric flow rate of gaz (Kg/s)</param>
        /// <param name="PCI">PCI : Lower heating value (J/Kg)</param>
        /// <returns></returns>
 
        static double equation22(double D, double PCI)
        {
            double P = D * PCI;
            return P;
        }

	}//end Equation

}//end namespace Modelisator.Model