///////////////////////////////////////////////////////////
//  GrandeurPhysique.cs
//  Implementation of the Class GrandeurPhysique
//  Generated by Enterprise Architect
//  Created on:      11-juin-2015 10:49:21
///////////////////////////////////////////////////////////




using Modelisator.Model;
namespace Modelisator.Model
{
	public class GrandeurPhysique {

		private string Nom;
		private string Unite;
		private double Valeur;
		private string Description;
		private bool Calcule;
		private bool Selectionne;
		private bool EstPremier;
		public Produit m_Produit;
		public Equation m_Equation;

		public GrandeurPhysique(){

		}

		~GrandeurPhysique(){

		}

		public virtual void Dispose(){

		}

	}//end GrandeurPhysique

}//end namespace System