///////////////////////////////////////////////////////////
//  Produit.cs
//  Implementation of the Class Produit
//  Generated by Enterprise Architect
//  Created on:      11-juin-2015 10:49:21
///////////////////////////////////////////////////////////




namespace System {
	public class Produit {

		private string Nom;
		private string Description;
		private bool Selectionne;

		public Produit(){

		}

		~Produit(){

		}

		public virtual void Dispose(){

		}

	}//end Produit

}//end namespace System