///////////////////////////////////////////////////////////
//  Relation.cs
//  Implementation of the Class Relation
//  Generated by Enterprise Architect
//  Created on:      17-juin-2015 09:38:57
//  Original author: Quentin
///////////////////////////////////////////////////////////
using System;
using System.Collections.Generic;
using System.Text;
using System.Threading.Tasks;
using Modelisator.Model;

namespace Modelisator.Model {
	public class Relation {

		private GrandeurPhysique m_Arrivee;

		private GrandeurPhysique m_Debut;

		public List<Equation> Equations;

        static public int[][] MatriceRelations;

		public Relation(){		}

		public GrandeurPhysique Arrivee{
			get{
                return m_Arrivee;
			}
			set{
                m_Arrivee = value;
			}
		}

		public GrandeurPhysique Debut{
			get{
                return m_Debut;
			}
			set{
                m_Debut = value;
			}
		}


        static public void EnnumRelation()
        {
            int tailleTab = Produit.GrandeurPhysiques.Count;
            MatriceRelations = new int[tailleTab][];
            for (int i = 0; i < tailleTab; i++)
            {
                MatriceRelations[i] = new int[tailleTab];
            }

            for (int i = 0; i < tailleTab; i++)
            {
                for (int j = 0; j < tailleTab; j++)
                {
                    MatriceRelations[i][j] = 0;
                }
            }

            //Pression
            MatriceRelations[Produit.GrandeurPhysiques["p"].iM][Produit.GrandeurPhysiques["X1"].iM] = 1; //[0][1]
            MatriceRelations[Produit.GrandeurPhysiques["p"].iM][Produit.GrandeurPhysiques["Tmax"].iM] = 1; //[0][2]
            MatriceRelations[Produit.GrandeurPhysiques["p"].iM][Produit.GrandeurPhysiques["p0"].iM] = 1; //[0][3]
            MatriceRelations[Produit.GrandeurPhysiques["p"].iM][Produit.GrandeurPhysiques["sigma"].iM] = 9; //[0][6]
            MatriceRelations[Produit.GrandeurPhysiques["p"].iM][Produit.GrandeurPhysiques["R"].iM] = 9; //[0][7]
            MatriceRelations[Produit.GrandeurPhysiques["p"].iM][Produit.GrandeurPhysiques["t"].iM] = 9; //[0][8]
            MatriceRelations[Produit.GrandeurPhysiques["p"].iM][Produit.GrandeurPhysiques["tu"].iM] = 13; //[0][9]
            MatriceRelations[Produit.GrandeurPhysiques["p"].iM][Produit.GrandeurPhysiques["sigma_y"].iM] = 13; //[0][10]

            //X1
            MatriceRelations[Produit.GrandeurPhysiques["X1"].iM][Produit.GrandeurPhysiques["p"].iM] = 2; //[1][0]
            MatriceRelations[Produit.GrandeurPhysiques["X1"].iM][Produit.GrandeurPhysiques["Tmax"].iM] = 2; //[1][2]
            MatriceRelations[Produit.GrandeurPhysiques["X1"].iM][Produit.GrandeurPhysiques["p0"].iM] = 2; //[1][3]

            //Tmax
            MatriceRelations[Produit.GrandeurPhysiques["Tmax"].iM][Produit.GrandeurPhysiques["p"].iM] = 3; //[2][0]
            MatriceRelations[Produit.GrandeurPhysiques["Tmax"].iM][Produit.GrandeurPhysiques["X1"].iM] = 3; //[2][1]
            MatriceRelations[Produit.GrandeurPhysiques["Tmax"].iM][Produit.GrandeurPhysiques["p0"].iM] = 3; //[2][3]
            MatriceRelations[Produit.GrandeurPhysiques["Tmax"].iM][Produit.GrandeurPhysiques["dV"].iM] = 6; //[2][4]
            MatriceRelations[Produit.GrandeurPhysiques["Tmax"].iM][Produit.GrandeurPhysiques["alpha_gas"].iM] = 6; //[2][5]

            //p0
            MatriceRelations[Produit.GrandeurPhysiques["p0"].iM][Produit.GrandeurPhysiques["p"].iM] = 4; //[3][0]
            MatriceRelations[Produit.GrandeurPhysiques["p0"].iM][Produit.GrandeurPhysiques["X1"].iM] = 4; //[3][1]
            MatriceRelations[Produit.GrandeurPhysiques["p0"].iM][Produit.GrandeurPhysiques["Tmax"].iM] = 4; //[3][2]

            //dV
            MatriceRelations[Produit.GrandeurPhysiques["dV"].iM][Produit.GrandeurPhysiques["alpha_gas"].iM] = 5; //[4][5]
            MatriceRelations[Produit.GrandeurPhysiques["dV"].iM][Produit.GrandeurPhysiques["Tmax"].iM] = 5; //[4][2]

            //alpha_gas
            MatriceRelations[Produit.GrandeurPhysiques["alpha_gas"].iM][Produit.GrandeurPhysiques["dV"].iM] = 7; //[5][4]
            MatriceRelations[Produit.GrandeurPhysiques["alpha_gas"].iM][Produit.GrandeurPhysiques["Tmax"].iM] = 7; //[5][2]

            //sigma
            MatriceRelations[Produit.GrandeurPhysiques["sigma"].iM][Produit.GrandeurPhysiques["p"].iM] = 8; //[6][0]
            MatriceRelations[Produit.GrandeurPhysiques["sigma"].iM][Produit.GrandeurPhysiques["R"].iM] = 8; //[6][7]
            MatriceRelations[Produit.GrandeurPhysiques["sigma"].iM][Produit.GrandeurPhysiques["t"].iM] = 8; //[6][8]

            //R
            MatriceRelations[Produit.GrandeurPhysiques["R"].iM][Produit.GrandeurPhysiques["p"].iM] = 10; //[7][0]
            MatriceRelations[Produit.GrandeurPhysiques["R"].iM][Produit.GrandeurPhysiques["sigma"].iM] = 10; //[7][6]
            MatriceRelations[Produit.GrandeurPhysiques["R"].iM][Produit.GrandeurPhysiques["t"].iM] = 10; //[7][8]
            MatriceRelations[Produit.GrandeurPhysiques["R"].iM][Produit.GrandeurPhysiques["tu"].iM] = 14; //[7][9]
            MatriceRelations[Produit.GrandeurPhysiques["R"].iM][Produit.GrandeurPhysiques["sigma_y"].iM] = 14; //[7][10]

            //t
            MatriceRelations[Produit.GrandeurPhysiques["t"].iM][Produit.GrandeurPhysiques["p"].iM] = 11; //[8][0]
            MatriceRelations[Produit.GrandeurPhysiques["t"].iM][Produit.GrandeurPhysiques["R"].iM] = 11; //[8][7]
            MatriceRelations[Produit.GrandeurPhysiques["t"].iM][Produit.GrandeurPhysiques["sigma"].iM] = 11; //[8][6]
            MatriceRelations[Produit.GrandeurPhysiques["t"].iM][Produit.GrandeurPhysiques["delta_t"].iM] = 17; //[8][11]

            //tu
            MatriceRelations[Produit.GrandeurPhysiques["tu"].iM][Produit.GrandeurPhysiques["p"].iM] = 12; //[9][0]
            MatriceRelations[Produit.GrandeurPhysiques["tu"].iM][Produit.GrandeurPhysiques["R"].iM] = 12; //[9][7]
            MatriceRelations[Produit.GrandeurPhysiques["tu"].iM][Produit.GrandeurPhysiques["sigma_y"].iM] = 12; //[9][10]
            MatriceRelations[Produit.GrandeurPhysiques["tu"].iM][Produit.GrandeurPhysiques["delta_t"].iM] = 18; //[9][11]

            //sigma_y
            MatriceRelations[Produit.GrandeurPhysiques["sigma_y"].iM][Produit.GrandeurPhysiques["p"].iM] = 15; //[10][0]
            MatriceRelations[Produit.GrandeurPhysiques["sigma_y"].iM][Produit.GrandeurPhysiques["R"].iM] = 15; //[10][7]
            MatriceRelations[Produit.GrandeurPhysiques["sigma_y"].iM][Produit.GrandeurPhysiques["tu"].iM] = 15; //[10][9]

            //delta_t
            MatriceRelations[Produit.GrandeurPhysiques["delta_t"].iM][Produit.GrandeurPhysiques["t"].iM] = 16; //[11][8]
            MatriceRelations[Produit.GrandeurPhysiques["delta_t"].iM][Produit.GrandeurPhysiques["tu"].iM] = 16; //[11][9]
 

        }

	}//end Relation

}//end namespace Modelisator.Model