///////////////////////////////////////////////////////////
//  Equation.cs
//  Implementation of the Class Equation
//  Generated by Enterprise Architect
//  Created on:      11-juin-2015 10:49:21
//  Original author: Quentin
///////////////////////////////////////////////////////////




namespace System {
	public class Equation {

		private int NbrGP;
		private int NbrGPConnus;

		public Equation(){

		}

		~Equation(){

		}

		public virtual void Dispose(){

		}

		public double Calculer(){

			return 0;
		}

	}//end Equation

}//end namespace System