///////////////////////////////////////////////////////////
//  Relation.cs
//  Implementation of the Class Relation
//  Generated by Enterprise Architect
//  Created on:      11-juin-2015 10:49:21
//  Original author: Quentin
///////////////////////////////////////////////////////////




using System;
namespace System {
	public class Relation {

		private GrandeurPhysique Debut;
		private GrandeurPhysique Arrivee;
		public Equation m_Equation;
		public GrandeurPhysique m_GrandeurPhysique;

		public Relation(){

		}

		~Relation(){

		}

		public virtual void Dispose(){

		}

	}//end Relation

}//end namespace System