///////////////////////////////////////////////////////////
//  Utilisateur.cs
//  Implementation of the Class Utilisateur
//  Generated by Enterprise Architect
//  Created on:      11-juin-2015 10:49:21
///////////////////////////////////////////////////////////




using System;
namespace System {
	public class Utilisateur {

		private string Nom;
		private string MotDePasse;
		private Groupe Groupe;
		public Contexte m_Contexte;

		public Utilisateur(){

		}

		~Utilisateur(){

		}

		public virtual void Dispose(){

		}

	}//end Utilisateur

}//end namespace System