///////////////////////////////////////////////////////////
//  Equation.cs
//  Implementation of the Class Equation
//  Generated by Enterprise Architect
//  Created on:      17-juin-2015 09:38:57
//  Original author: Quentin
///////////////////////////////////////////////////////////




namespace Modelisator.Model {
	public class Equation {

		private int NbrGP{
			//read property
			get{;}
			//write property
			set{;}
		}
		private int NbrGPConnus{
			//read property
			get{;}
			//write property
			set{;}
		}

		public Equation(){

		}

		~Equation(){

		}

		public virtual void Dispose(){

		}

		public double Calculer(){

			return 0;
		}

		public int NbrGP{
			get{
				return NbrGP;
			}
			set{
				NbrGP = value;
			}
		}

		public int NbrGPConnus{
			get{
				return NbrGPConnus;
			}
			set{
				NbrGPConnus = value;
			}
		}

	}//end Equation

}//end namespace Modelisator.Model