///////////////////////////////////////////////////////////
//  Groupe.cs
//  Implementation of the Class Groupe
//  Generated by Enterprise Architect
//  Created on:      17-juin-2015 09:38:57
//  Original author: Quentin
///////////////////////////////////////////////////////////




namespace Modelisator.Model {
	public class Groupe {

		private string Nom{
			//read property
			get{;}
			//write property
			set{;}
		}

		public Groupe(){

		}

		~Groupe(){

		}

		public virtual void Dispose(){

		}

		public string Nom{
			get{
				return Nom;
			}
			set{
				Nom = value;
			}
		}

	}//end Groupe

}//end namespace Modelisator.Model